#!/usr/bin/env bash

function usage() {
  cat <<EOF
Usage: $0 [OPTION]
    Test this or an optionally provided target image to meet Invoca's standards
    -i, --image     If provided, will run the tests against this image
    -h, --help      Displays this help menu and exits
EOF
  exit $1
}

function serverspec() {
    docker run --rm --name image-test \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd):/image-test \
        -w /image-test \
        -e IMAGE_ID=$1 \
        jadametz/serverspec \
        spec/
}

while test $# -gt 0; do
    case "$1" in
    (-i | --image)
        shift
            serverspec $1
        shift
        ;;
    (-h | --help)
        usage 0
        ;;
    (*)
        usage 1
        ;;
    esac
    shift
done
